fix: syntax

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -9,39 +9,39 @@ on:
 jobs:
   test:
     name: Ping the E2E Repo, Return the Unique Workflow Run ID, and Return the Result of the Workflow
-      runs-on: ubuntu-latest
-      steps:
-        - name: Checkout the branch pinging the E2E Repository
-        - uses: actions/checkout@v3
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout the branch pinging the E2E Repository
+      - uses: actions/checkout@v3
 
-        - name: Dispatch and return Run ID
-          uses: codex-/return-dispatch@v1.5.0
-          id: return-dispatch
-          with:
-            token: ${{ secrets.ACCESS_TOKEN }} # Note this is NOT GITHUB_TOKEN but a PAT
-            ref: chore/sc-7778/if-a-test-fails-in-the-e2e-repo-it-gets-reflected # or refs/heads/target_branch
-            repo: aoeu-e2e
-            owner: theartofeducation
-            workflow: test.yml
-            workflow_inputs: '{"cake":"delicious"}'
-            workflow_timeout_seconds: 300 # Default: 300
-        
-        - name: Output fetched Run ID
-          run: echo ${{ steps.return-dispatch.outputs.run_id }}
+      - name: Dispatch and return Run ID
+        uses: codex-/return-dispatch@v1.5.0
+        id: return-dispatch
+        with:
+          token: ${{ secrets.ACCESS_TOKEN }} # Note this is NOT GITHUB_TOKEN but a PAT
+          ref: chore/sc-7778/if-a-test-fails-in-the-e2e-repo-it-gets-reflected # or refs/heads/target_branch
+          repo: aoeu-e2e
+          owner: theartofeducation
+          workflow: test.yml
+          workflow_inputs: '{"cake":"delicious"}'
+          workflow_timeout_seconds: 300 # Default: 300
+      
+      - name: Output fetched Run ID
+        run: echo ${{ steps.return-dispatch.outputs.run_id }}
 
-        - name: Evaluate that the Run ID output has been set
-          run: |
-            if [ "${{ steps.return-dispatch.outputs.run_id }}" == "" ]; then
-              echo "Failed to return Run ID and trying to test a test failure"
-              exit 1
-            fi
+      - name: Evaluate that the Run ID output has been set
+        run: |
+          if [ "${{ steps.return-dispatch.outputs.run_id }}" == "" ]; then
+            echo "Failed to return Run ID and trying to test a test failure"
+            exit 1
+          fi
 
-        - name: Await Run ID Test Results ${{ steps.return-dispatch.outputs.run_id }}
-          uses: Codex-/await-remote-run@v1.4.0
-          with:
-            token: ${{ secrets.PERSONAL_TOKEN }}
-            repo: aoeu-e2e
-            owner: theartofeducation
-            run_id: ${{ steps.return-dispatch.outputs.run_id }}
-            run_timeout_seconds: 300 # Optional
-            poll_interval_ms: 5000 # Optional
+      - name: Await Run ID Test Results ${{ steps.return-dispatch.outputs.run_id }}
+        uses: Codex-/await-remote-run@v1.4.0
+        with:
+          token: ${{ secrets.PERSONAL_TOKEN }}
+          repo: aoeu-e2e
+          owner: theartofeducation
+          run_id: ${{ steps.return-dispatch.outputs.run_id }}
+          run_timeout_seconds: 300 # Optional
+          poll_interval_ms: 5000 # Optional
